export const registryAbi = [
  {
    type: "function",
    name: "EXECUTOR_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "canSettleTrade",
    inputs: [{ name: "tradeId", type: "uint256" }],
    outputs: [
      { name: "settleable", type: "bool" },
      { name: "expectedStatus", type: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executorForceSettle",
    inputs: [
      { name: "tradeId", type: "uint256" },
      { name: "marketPrice", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getTrade",
    inputs: [{ name: "tradeId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "tradeId", type: "uint256" },
          { name: "creator", type: "address" },
          { name: "asset", type: "string" },
          { name: "direction", type: "uint8" },
          { name: "entryPrice", type: "uint256" },
          { name: "stopLossLower", type: "uint256" },
          { name: "stopLossUpper", type: "uint256" },
          { name: "takeProfitLower", type: "uint256" },
          { name: "takeProfitUpper", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "expiry", type: "uint256" },
          { name: "stakeAmount", type: "uint256" },
          { name: "status", type: "uint8" },
          { name: "settlementPrice", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTreasuryBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserBalance",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextTradeId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "peekPrice",
    inputs: [{ name: "asset", type: "string" }],
    outputs: [
      { name: "price1e8", type: "uint256" },
      { name: "publishTime", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewSettlement",
    inputs: [{ name: "tradeId", type: "uint256" }],
    outputs: [
      { name: "settleable", type: "bool" },
      { name: "expectedStatus", type: "uint8" },
      { name: "marketPrice", type: "uint256" },
      { name: "payoutAmount", type: "uint256" },
      { name: "pnl", type: "int256" },
      { name: "priceFresh", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quoteUpdateFee",
    inputs: [{ name: "priceUpdateData", type: "bytes[]" }],
    outputs: [{ name: "feeAmount", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "settleBatch",
    inputs: [
      { name: "tradeIds", type: "uint256[]" },
      { name: "priceUpdateData", type: "bytes[]" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "settleTrade",
    inputs: [
      { name: "tradeId", type: "uint256" },
      { name: "priceUpdateData", type: "bytes[]" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "totalTrades",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
] as const;
